/**
 * What a children's picture book must never be about.
 *
 * Grouped by *why* a term is blocked rather than by language, because the user
 * message names the reason ("this idea contains violence"), and that reads the
 * same whichever language the term was written in.
 *
 * ## How to add a term
 *
 * - Write the **whole word**, and write the forms separately (`kill`, `kills`,
 *   `killed`, `killing`, `killer`). Matching is word-anchored for Latin script,
 *   so a bare stem does not catch its own inflections — and listing them
 *   explicitly is what keeps `ass` from matching `class` and `glass`.
 * - Leave out anything a children's story can innocently contain. `hit`, `shot`
 *   and `fight` are absent on purpose: a ball game, a photo and a pillow fight
 *   are all ordinary picture-book material, and a false positive here means a
 *   parent cannot make the book they wanted.
 * - For Chinese, prefer two-character terms over single characters. There are no
 *   word boundaries in Chinese text, so a single character matches inside every
 *   compound it appears in — `枪` would block `水枪` (water pistol), `刀` would
 *   block `剪刀` (scissors). The four single characters below (`杀`, `淫`, `娼`,
 *   `嫖`) are the exceptions, kept because they cannot appear in a children's
 *   book innocently; the one compound of `杀` that can is in `ALLOWED_PHRASES`.
 */
export type ModerationCategory =
  | 'sexual'
  | 'violence'
  | 'self_harm'
  | 'hate'
  | 'substances'
  | 'profanity'
  | 'other';

export const BLOCKED_TERMS: Record<ModerationCategory, string[]> = {
  sexual: [
    // English
    'sex',
    'sexual',
    'sexually',
    'sexuality',
    'sexy',
    'porn',
    'porno',
    'pornography',
    'nude',
    'nudes',
    'naked',
    'nudity',
    'erotic',
    'orgasm',
    'orgy',
    'rape',
    'raped',
    'rapist',
    'molest',
    'molested',
    'molestation',
    'incest',
    'prostitute',
    'prostitution',
    'brothel',
    'stripper',
    'strip club',
    'pedophile',
    'paedophile',
    'hentai',
    'fetish',
    'bondage',
    'sadomasochism',
    // 中文
    '色情',
    '情色',
    '黄色网站',
    '做爱',
    '性交',
    '性爱',
    '性行为',
    '性器官',
    '性虐待',
    '强奸',
    '强暴',
    '轮奸',
    '猥亵',
    '卖淫',
    '娼',
    '妓女',
    '嫖',
    '淫',
    '裸体',
    '裸露',
    '全裸',
    '裸照',
    '乱伦',
    '恋童',
    '幼交',
    '黄片',
    '毛片',
    'av女优',
  ],
  violence: [
    // English
    'kill',
    'kills',
    'killed',
    'killing',
    'killer',
    'murder',
    'murders',
    'murdered',
    'murderer',
    'massacre',
    'slaughter',
    'slaughtered',
    'behead',
    'beheaded',
    'decapitate',
    'stab',
    'stabs',
    'stabbed',
    'stabbing',
    'torture',
    'tortured',
    'torturing',
    'gore',
    'gory',
    'blood',
    'bloody',
    'bloodshed',
    'corpse',
    'mutilate',
    'mutilated',
    'dismember',
    'gun',
    'guns',
    'handgun',
    'pistol',
    'rifle',
    'shotgun',
    'machine gun',
    'bullet',
    'bullets',
    'bomb',
    'bombs',
    'bombing',
    'grenade',
    'explosive',
    'explosives',
    'landmine',
    'weapon',
    'weapons',
    'knife',
    'knives',
    'machete',
    'war',
    'warfare',
    'execution',
    'executed',
    'executing',
    'executions',
    'cruelty',
    'abuse',
    'abused',
    'abusive',
    'poison',
    'poisoned',
    'poisoning',
    'strangle',
    'strangled',
    'strangling',
    'suicide bomb',
    'terrorist',
    'terrorism',
    // 中文
    '杀',
    '谋杀',
    '凶杀',
    '砍死',
    '打死',
    '刺死',
    '枪杀',
    '开枪',
    '手枪',
    '步枪',
    '机枪',
    '炸弹',
    '爆炸',
    '手榴弹',
    '地雷',
    '武器',
    '砍刀',
    '匕首',
    '持刀',
    '虐待',
    '折磨',
    '殴打',
    '家暴',
    '尸体',
    '分尸',
    '血腥',
    '流血',
    '鲜血',
    '血肉模糊',
    '投毒',
    '下毒',
    '恐怖袭击',
    '恐怖分子',
  ],
  self_harm: [
    // English
    'suicide',
    'suicidal',
    'suicides',
    'self harm',
    'cutting myself',
    'anorexia',
    'bulimia',
    'starve myself',
    // 中文
    '自杀',
    '自残',
    '自伤',
    '割腕',
    '跳楼',
    '上吊',
    '不想活了',
    '轻生',
    '绝食',
    '厌食症',
  ],
  hate: [
    // English
    'nigger',
    'niggers',
    'nigga',
    'niggas',
    'faggot',
    'faggots',
    'retard',
    'retarded',
    'retards',
    'kike',
    'kikes',
    'spic',
    'spics',
    'chink',
    'chinks',
    'wetback',
    'wetbacks',
    'tranny',
    'trannies',
    'nazi',
    'nazis',
    'neo nazi',
    'white power',
    'supremacist',
    'jihad',
    'isis',
    // 中文
    '纳粹',
    '希特勒',
    '种族灭绝',
    '劣等民族',
    '东亚病夫',
  ],
  substances: [
    // English
    'drug',
    'drugs',
    'cocaine',
    'heroin',
    'meth',
    'methamphetamine',
    'marijuana',
    'cannabis',
    'opium',
    'ecstasy',
    'mdma',
    'ketamine',
    'overdose',
    'drug dealer',
    'smoke',
    'smokes',
    'smoked',
    'smoker',
    'smokers',
    'cigarette',
    'cigarettes',
    'smoking',
    'vape',
    'vapes',
    'vaped',
    'vaping',
    'drunk',
    'drunkard',
    'gamble',
    'gambles',
    'gambled',
    'gambling',
    'casino',
    'casinos',
    // 中文
    '毒品',
    '吸毒',
    '贩毒',
    '冰毒',
    '海洛因',
    '大麻',
    '摇头丸',
    '可卡因',
    '鸦片',
    '香烟',
    '吸烟',
    '抽烟',
    '电子烟',
    '酗酒',
    '醉酒',
    '赌博',
    '赌场',
  ],
  profanity: [
    // English
    'fuck',
    'fucks',
    'fucked',
    'fucking',
    'fucker',
    'motherfucker',
    'shit',
    'shits',
    'shitty',
    'shitting',
    'shithead',
    'bullshit',
    'bitch',
    'bitches',
    'bastard',
    'asshole',
    'assholes',
    'ass',
    'arse',
    'arsehole',
    'dick',
    'dicks',
    'dickhead',
    'cock',
    'cocks',
    'pussy',
    'cunt',
    'cunts',
    'whore',
    'whores',
    'slut',
    'sluts',
    'damn',
    'goddamn',
    'hell',
    'piss',
    'pissed',
    'wanker',
    'bollocks',
    'bugger',
    // 中文
    '操你妈',
    '草你妈',
    '草泥马',
    '傻逼',
    '傻B',
    '他妈的',
    '狗娘养的',
    '贱人',
    '婊子',
    '王八蛋',
    '滚蛋',
  ],
  other: [
    // English
    'occult',
    'satanic',
    'satanist',
    'séance',
    'seance',
    'exorcism',
    'demonic',
    'ritual sacrifice',
    'human trafficking',
    // 中文
    '邪教',
    '撒旦教',
    '献祭',
    '人体实验',
    '虐待动物',
  ],
};

/**
 * Innocent phrases hidden from the matcher before it runs.
 *
 * Removal, not exclusion: the phrase is blanked out of the text, and the
 * blocked term is then matched against what is left. So `杀菌` (sterilise) is
 * allowed while a bare `杀` still is not — this list is the only reason the
 * single-character Chinese terms can be on the list at all.
 *
 * There is no English section, and that is the point: Latin-script terms are
 * word-anchored, so `hell` does not match `hello`, `ass` does not match
 * `class`, and `sex` does not match `sextant`. Only Chinese, which has no word
 * boundaries, needs a list.
 */
export const ALLOWED_PHRASES: string[] = [
  '杀菌',
  '杀虫',
  '消毒',
  // 大麻 (marijuana) sits inside 大麻烦 (big trouble) and 大麻袋 (a big sack),
  // both of which belong in a children's book.
  '大麻烦',
  '大麻袋',
  '大麻布',
  '大麻绳',
  '大麻花',
  // Harmless compounds of the violence terms: tying a tight knot, working
  // hard, and a boom in knowledge.
  '打死结',
  '流血流汗',
  '信息爆炸',
  '知识爆炸',
];

/**
 * Everything blocked, flattened once at load so a request is a few hundred
 * regex tests over a string of at most a few hundred characters.
 */
export const BLOCKED_FLAT: { term: string; category: ModerationCategory }[] =
  Object.entries(BLOCKED_TERMS).flatMap(([category, terms]) =>
    terms.map((term) => ({ term, category: category as ModerationCategory }))
  );
